# -*- coding: utf-8 -*-
"""Copy of Data-and-bias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAN_tcqLt05GIvfNb5MNAhdHciBlR7r3

# CIT 5001 Data and Bias
<img src="https://quantumzeitgeist.com/wp-content/uploads/pythonai.jpeg" height=200px>

Click on **File/Save a Copy in Drive** to make your own editable copy that will save your changes.

## Resume Dataset

Many companies now use AI to do the first screening through resumes submitted for jobs. They (or the 3rd party software they use) train the AI to look for certain required skills.

The following dataset with made-up resume data keeps track of the characteristics of the received resumes such as the number of years of experience, education level, number of github projects, whether the candidate is Local, InState, or OutState, whether they have the required skills, and their gender. The last column is whether the decision to hire was YES or NO. This could be used to train an AI.

Let's first read in the data into a Pandas dataframe which is like a table or spreadsheet.
"""

import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/bhoffman0/data-sets/refs/heads/main/resume-dataset.csv")
data.head()

"""## Describe the data

First do some data exploration with info() for meta-data and describe() for some statistics like averages/means and len(data) for how many rows.
"""

# 1. How many rows of data are there in this file?
print("Number of rows:", len(data))

"""## Is the data balanced?

Let's see how balanced the data is. Do we have about equal numbers of YES and NO hiring decisions? Do we have about equal numbers of Male and Female candidates?

Count how many times each unique value appears in a column with value_counts:

data.columnname.value_counts()    or
data['columnname'].value_counts()

"""

# Count how many YES or NO hiring decisions
data.Hire.value_counts()




print("Hiring decisions:")
print(data.Hire.value_counts())



# TODO (Answer):
# 2. Is the data is balanced with similar numbers of YES/NO hiring decisions?
# 3. Is the data balanced with similar numbers of Male/Female data?
print("\nGender counts:")
print(data.Gender.value_counts())

"""## Bar Charts

Make simple bar charts with .plot(kind="bar").

data.plot(kind="bar") or data.hist() will only plot columns with numerical values. Sometimes data scientists convert all values to numbers so that they are easier to graph and train from. For text values, you must use value_counts() before plotting.

"""

# Bar chart for Hire column
HireColumnCounts = data.Hire.value_counts()
HireColumnCounts.plot(kind="bar")


# TODO: Make a bar chart for the Gender column
GenderColumnCounts = data.Gender.value_counts()
GenderColumnCounts.plot(kind="bar")

"""## Data Subsets: Filter Rows for Hired and NotHired

Let's make two data subsets for those Hired and Not Hired and analyze them.

Filter/pull out certain rows with a specific value (boolean masking/indexing)

data[ data.columnname == 'value' ]

"""

# Create a hired data subset
hired = data[ data["Hire"] == "YES" ]
len(hired)

# TODO: Create a notHired subset
notHired = data[ data["Hire"] == "NO" ]
len(notHired)
# TODO: From hired, create a hiredM and hiredF data subsets for Gender M or F.
hiredM = hired[ hired["Gender"] == "M" ]
hiredF = hired[ hired["Gender"] == "F" ]

print("Hired M:", len(hiredM))
print("Hired F:", len(hiredF))

"""## Analyze Subsets for Data Bias

Using the data subsets of hired, notHired, hiredM, hiredF, use value_counts, bar charts, and or pd.crosstab(col1,col2) to analyze the columns ExperienceYears, EducationLevel,	RequiredSkills, and	Gender with Hire.
"""

# Use value_counts() and plot for different columns in hired or notHired
skillsHired = hired.RequiredSkills.value_counts()
print("Percentage of hired who have required skills:", round(skillsHired["Y"]/len(hired) * 100, 2), "%")

# Use pd.crosstab to compare columns in data
pd.crosstab(data.RequiredSkills, data.Hire)

# TODO: Use value_counts() and percentage or plot for the Gender column and at least 1 more column in hired or notHired
print("Hired gender counts:")
print(hired["Gender"].value_counts())
print("Hired gender percentages:")
print(hired["Gender"].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

# Education counts
print("Hired education counts:")
print(hired["EducationLevel"].value_counts())
print("Hired education percentages:")
print(hired["EducationLevel"].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

# TODO: Now compare hiredM and hiredF for value_counts of at least 2 more columns
print("Male hires - education counts:")
print(hiredM["EducationLevel"].value_counts())
print("Male hires - education percentages:")
print(hiredM["EducationLevel"].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

# compare required skills

print("Male hires - required skills counts:")
print(hiredM["RequiredSkills"].value_counts())
print("Male hires - required skills percentages:")
print(hiredM["RequiredSkills"].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

print("Hiring percentage within each gender:")
print(pd.crosstab(data.Gender, data.Hire, normalize='index').mul(100).round(2).astype(str) + '%')

# Calculate the average ExperienceYears for hired vs notHired
avg_exp_hired = hired['ExperienceYears'].mean()
avg_exp_nothired = notHired['ExperienceYears'].mean()

print(f"Average Experience (Hired): {avg_exp_hired:.2f} years")
print(f"Average Experience (Not Hired): {avg_exp_nothired:.2f} years")

# Also let's look at the summary grouped by Hire status
display(data.groupby('Hire')['ExperienceYears'].describe())

"""## Discussion
The  dataset had nearly equal hire and not hired counts, but hiring rates differed by gender:68.18 % for Men versus 21.43% for Woman, seggesting possible gender bias.An AItraines on these patterns could repeat unfair hiring decisions, so futher fainess testing would be important.

## Gemini AI in Colab

Use Gemini AI to write code to answer a question that you are interested in about this data set. Write your question here and the code. Make sure you understand the code. Was it able to find the answer to your question?

Do Share, Anyone can view, and copy the link to turn this in on Moodle.
"""